### ISSUE TITLE
Is there a way to have dynamic set name?

### ISSUE THREAD

**Issue by Alexx-G** [aerospike/spring-data-aerospike#454]
IIRC the only way to customize a set name is by providing `collection` parameter to `Document` parameter.
This doesn't work when I'd like to shard the same entity by different sets (e.g. by including some sharding criteria in the set name).
Defining new entities doesn't scale in case some kind of tenant id should be included in the set name.

What the easiest way to get this kind of setup working?

**Comment by roimenashe** [comment]
If i'm not mistaken - currently there is no way to achieve that using Spring Data Aerospike.
In order to dynamically set the `collection` field of `@Document` annotation - SpEL (Spring Expression Language) is required and not supported at the moment on `collection` field.

There is a plan to support injecting the collection/set name in `AerospikeOperations` operations exactly for these purposes.

The only way to do it right now is to use the Aerospike Java Client (you can utilize the client's bean that was defined in the configuration that uses Spring Data Aerospike behind the scenes).

**Comment by Alexx-G** [comment]
Thanks @roimenashe ! Injecting set name to AerospikeOperation would cover my use case as well. 👍

**Comment by qihaiyan** [comment]
I do this by a CustomQueryEnging which extends QueryEnging and dynamicaly change set name in `public KeyRecordIterator select(String namespace, String set, String[] binNames, Filter filter, Qualifier... qualifiers)` method.

**Comment by roimenashe** [comment]
@Alexx-G @qihaiyan Set name parameter in AerospikeOperations/AerospikeTemplate will be officially supported in the next version of Spring Data Aerospike (probably 4.6.0), thanks for bringing that up!
